version: 1

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  go:
    format: 'time="%(asctime)s" level=%(levelname)s msg="%(message)s" logger=%(name)s'
    datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
    delay: True

  rich:
    class: kedro.logging.RichHandler
    rich_tracebacks: True

  basic:
    class: logging.StreamHandler
    formatter: go

root:
  level: INFO
  handlers: [rich, info_file_handler]
